### ISSUE TITLE
Traceback on averageHR

### ISSUE THREAD

**Issue by wschoot** [torandi/garmin-wrapped#1]
Hi!

I tried your code but it gives me a traceback:

```
Getting info for year 2023

WARNING:root:Unknown sport id 89, parent: 17, key: multi_sport. Ignored.
WARNING:root:Unknown sport id 89, parent: 17, key: multi_sport. Ignored.
WARNING:root:Unknown sport id 89, parent: 17, key: multi_sport. Ignored.
WARNING:root:Unknown sport id 89, parent: 17, key: multi_sport. Ignored.
WARNING:root:Unknown sport id 164, parent: 4, key: breathwork. Ignored.
WARNING:root:Unknown sport id 162, parent: 4, key: auto_racing. Ignored.
WARNING:root:Unknown sport id 89, parent: 17, key: multi_sport. Ignored.
WARNING:root:Unknown sport id 226, parent: 219, key: paddelball. Ignored.
WARNING:root:Unknown sport id 164, parent: 4, key: breathwork. Ignored.
WARNING:root:Unknown sport id 11, parent: 29, key: indoor_cardio. Ignored.
WARNING:root:Unknown sport id 89, parent: 17, key: multi_sport. Ignored.
WARNING:root:Unknown sport id 89, parent: 17, key: multi_sport. Ignored.
WARNING:root:Unknown sport id 89, parent: 17, key: multi_sport. Ignored.
WARNING:root:Unknown sport id 238, parent: 228, key: sailing_v2. Ignored.
WARNING:root:Unknown sport id 89, parent: 17, key: multi_sport. Ignored.
WARNING:root:Unknown sport id 229, parent: 228, key: boating_v2. Ignored.
WARNING:root:Unknown sport id 4, parent: 17, key: other. Ignored.
WARNING:root:Unknown sport id 4, parent: 17, key: other. Ignored.
WARNING:root:Unknown sport id 89, parent: 17, key: multi_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 89, parent: 17, key: multi_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
Traceback (most recent call last):
  File "/Users/wouterschoot/git/garmin-wrapped/garmin-wrapped.py", line 290, in <module>
    summaries = {sport: sport_summary(sportsData) for sport,sportsData in grouped_activities.items() }
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wouterschoot/git/garmin-wrapped/garmin-wrapped.py", line 290, in <dictcomp>
    summaries = {sport: sport_summary(sportsData) for sport,sportsData in grouped_activities.items() }
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wouterschoot/git/garmin-wrapped/garmin-wrapped.py", line 176, in sport_summary
    avgHrSum += act['averageHR']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
```
I think it tries to find heartrate data from an activity that has none, could that be the culprit?

```
$ python3 --version
Python 3.11.7
```

**Comment by torandi** [comment]
Ah thanks for the report, I'll take a look after work today :)

As you say, probably probably an activity without HR, I just assumed everything had one.

I'll add the some of the sports too (especially "multi_sport").

**Comment by torandi** [comment]
This should have been fixed with my latest commit. Please test it and let me know if you still have issues.

**Comment by wschoot** [comment]
Heya! 

It now works, so thats great. I do get some warnings about some not-included sports but that's probably to be expected

```
Getting info for year 2023

WARNING:root:Unknown sport id 164, parent: 4, key: breathwork. Ignored.
WARNING:root:Unknown sport id 162, parent: 4, key: auto_racing. Ignored.
WARNING:root:Unknown sport id 164, parent: 4, key: breathwork. Ignored.
WARNING:root:Unknown sport id 11, parent: 29, key: indoor_cardio. Ignored.
WARNING:root:Unknown sport id 238, parent: 228, key: sailing_v2. Ignored.
WARNING:root:Unknown sport id 229, parent: 228, key: boating_v2. Ignored.
WARNING:root:Unknown sport id 4, parent: 17, key: other. Ignored.
WARNING:root:Unknown sport id 4, parent: 17, key: other. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
WARNING:root:Unknown sport id 182, parent: 4, key: e_sport. Ignored.
Data written to garmin-wrapped.json
```

**Comment by torandi** [comment]
Yeah, the warnings are about sports it doesn't recognize, and thus doesn't do any grouping on. If you want to include them, you can add them to the "topLevelSports" map at the top of garmin-wrapped.py, with their sport id (either it's own id, or a parent id).

They are still included in the totals atm.
